{"name": "test_negative_login_with_Wrong_User_Information_4___asdgmail____as123__________________", "status": "broken", "statusDetails": {"message": "TypeError: TestLoginFunctionality.test_negative_login_with_Wrong_User_Information() takes 3 positional arguments but 7 were given", "trace": "self = <tests.test_loginTest.TestLoginFunctionality testMethod=test_negative_login_with_Wrong_User_Information_4___asdgmail____as123__________________>\n\n    @wraps(func)\n    def wrapper(self):\n>       return func(self, *args, **kwargs)\nE       TypeError: TestLoginFunctionality.test_negative_login_with_Wrong_User_Information() takes 3 positional arguments but 7 were given\n\nvenv\\Lib\\site-packages\\ddt.py:220: TypeError"}, "start": 1677149215569, "stop": 1677149215569, "uuid": "5a26e1fc-a30c-4f09-9b9c-beb6eb6c1c62", "historyId": "70b91b15650c015229fdd0325c7b9735", "testCaseId": "2e9d7d3a55c5ad4d6d4e378fe49157cb", "fullName": "tests.test_loginTest.TestLoginFunctionality#test_negative_login_with_Wrong_User_Information_4___asdgmail____as123__________________", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_loginTest"}, {"name": "subSuite", "value": "TestLoginFunctionality"}, {"name": "host", "value": "DESKTOP-75D171T"}, {"name": "thread", "value": "13816-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_loginTest"}]}