{"name": "test_negative_login_with_Wrong_User_Information_5_______r1234__________________", "status": "broken", "statusDetails": {"message": "TypeError: TestLoginFunctionality.test_negative_login_with_Wrong_User_Information() takes 3 positional arguments but 7 were given", "trace": "self = <tests.test_loginTest.TestLoginFunctionality testMethod=test_negative_login_with_Wrong_User_Information_5_______r1234__________________>\n\n    @wraps(func)\n    def wrapper(self):\n>       return func(self, *args, **kwargs)\nE       TypeError: TestLoginFunctionality.test_negative_login_with_Wrong_User_Information() takes 3 positional arguments but 7 were given\n\nvenv\\Lib\\site-packages\\ddt.py:220: TypeError"}, "start": 1677149215583, "stop": 1677149215584, "uuid": "52a73e81-f152-4e49-93c6-de7983c2ded3", "historyId": "ee61d51ebc540f2abf436fff3b5a0005", "testCaseId": "e954dc6c24406b02ce113b355c124828", "fullName": "tests.test_loginTest.TestLoginFunctionality#test_negative_login_with_Wrong_User_Information_5_______r1234__________________", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_loginTest"}, {"name": "subSuite", "value": "TestLoginFunctionality"}, {"name": "host", "value": "DESKTOP-75D171T"}, {"name": "thread", "value": "13816-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_loginTest"}]}